logicalclocks/hopsmonitor-chef

templates/default/logstash/spark-streaming.conf.erb

Change hosts property to comply with logstash version retrieved by the cookbook

Change logstash config file

---

templates/default/admin.js.erb
templates/default/influxdb.conf.erb
templates/default/telegraf.conf.erb

add a dashboard for the admin and review the graphite configuration of influxdb to put all the namenode related values in the same measurement
https://hopshadoop.atlassian.net/browse/HOPSWORKS-74

HOPSWORKS-74

---

templates/default/logrotate.telegraf.erb

https://hopshadoop.atlassian.net/browse/HOPSWORKS-87

HOPSWORKS-87

---

files/default/auth
recipes/telegraf.rb

Change auth.log rotation policy
https://hopshadoop.atlassian.net/browse/HOPSWORKS-88

HOPSWORKS-88

---

recipes/_influxdb.rb

Create telegraf user before granting access to db
https://hopshadoop.atlassian.net/browse/HOPSWORKS-98

HOPSWORKS-98

---

recipes/_grafana.rb

setup admin.js when installing grafana
https://hopshadoop.atlassian.net/browse/HOPSWORKS-109

HOPSWORKS-109

---

templates/default/admin.js.erb
templates/default/spark.js.erb

change the admin and spark dashboard to better adapt when zooming in or out on the graph
https://hopshadoop.atlassian.net/browse/HOPSWORKS-110

HOPSWORKS-110

---

attributes/default.rb
metadata.rb
recipes/telegraf.rb
templates/default/hadoop-metrics2.properties.erb

overwrite hadoop-metrics configuration file to write metrics to influxDB
https://hopshadoop.atlassian.net/browse/HOPSWORKS-108
Alternative to hopshadoop/hops-hadoop-chef#38 (merge only one of them)

HOPSWORKS-108

---

Berksfile
Karamelfile
metadata.rb
recipes/_influxdb.rb
templates/default/metrics.properties.erb

Create metrics.properties and put to hdfs
https://hopshadoop.atlassian.net/browse/HOPSWORKS-185

HOPSWORKS-185

---

recipes/telegraf.rb
templates/default/telegraf.conf.erb

* Monitor ElasticSearch and ZooKeeeper only in the nodes where they are running
* Create telegraf log directory

HOPSWORKS-325

---

templates/default/admin.js.erb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-846

[HOPSWORKS-846] fix metrics in admin page

---

recipes/_grafana.rb
recipes/kapacitor.rb
templates/default/grafana.service.erb
templates/default/kapacitor.service.erb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1091

[HOPSWORKS-1091] Add systemd unit file deps

---

recipes/_grafana.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1095

[HOPSWORKS-1095] Add back Localhost support

---

files/default/dashboards/elastic.json

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1027
tests: https://github.com/logicalclocks/hops-testing/pull/512

[HOPSWORKS-1027] Add support for multiple elasticsearch nodes (HA)

---

files/default/dashboards/epipe.json

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1308
tests: https://github.com/logicalclocks/hops-testing/pull/598

[HOPSWORKS-1308][ePipe] Rewrite and fix the metrics code

---

files/default/dashboards/epipe.json

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1609
tests: https://github.com/logicalclocks/hops-testing/pull/645

[HOPSWORKS-1609][ePipe] Fix version conflicts in Elasticsearch

---

metadata.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1679

[HOPSWORKS-1679] pin version of java in Berksfile

---

recipes/alertmanager.rb
recipes/grafana.rb
recipes/influxdb.rb
recipes/node_exporter.rb
recipes/prometheus.rb

tests: https://github.com/logicalclocks/hops-testing-ee/pull/110

[HOPSWORKS-1862] Fix cyclic dependency error

---

recipes/prometheus.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1657

[HOPSWORKS-1657] Fix case when Prometheus recipe might run before consul

---

recipes/_security.rb
recipes/influxdb.rb
recipes/prometheus.rb
templates/default/influxdb.conf.erb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1657

[HOPSWORKS-1657] hopsmon user certificate for influxdb

---

recipes/_security.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1977

[HOPSWORKS-1977] Replace kagent/test with kagent/enabled

---

templates/default/alertmanager.service.erb
templates/default/grafana.service.erb
templates/default/influxdb.service.erb
templates/default/node_exporter.service.erb
templates/default/nvml_monitor.service.erb
templates/default/prometheus.service.erb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065

[HOPSWORKS-2065] Automatically restart failed systemd units

---

templates/default/alertmanager.service.erb
templates/default/grafana.service.erb
templates/default/influxdb.service.erb
templates/default/node_exporter.service.erb
templates/default/nvml_monitor.service.erb
templates/default/prometheus.service.erb

* [HOPSWORKS-2065] Automatically restart failed systemd units
* [HOPSWORKS-2065] Fix burst
[HOPSWORKS-2065]: https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065
[HOPSWORKS-2065]: https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065

[HOPSWORKS-2065] Automatically restart failed systemd units (#61)

---

recipes/node_exporter.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-2094

[HOPSWORKS-2094] Setup gpu monitoring even when gpu is not available but not start it

---

recipes/node_exporter.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-2682

[HOPSWORKS-2682] Register node_exporter with kagent services even if kagent is not enabled

---

attributes/default.rb
recipes/alertmanager.rb
recipes/install.rb
recipes/prometheus.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-2578

[HOPSWORKS-2578] Create Prometheus and Alertmanager data under data directory

---

recipes/node_exporter.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-2682

[HOPSWORKS-2682] Register node_exporter with kagent services even if kagent is not enabled (#75)

---

files/default/dashboards/onlinefs.json

(cherry picked from commit 27cc43db76d791187470cce249eff0a0615e4635)

[2.2] Online feature store dashboard

---

files/default/dashboards/onlinefs.json

(cherry picked from commit 4476b4b00c6c8db57bd4259f284182a9a0a0712f)

[Cherry-pick] Update OnlineFS dashboard (#73)

---

templates/default/grafana-consul.hcl.erb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-2748

[HOPSWORKS-2748] Fix Grafana's consul service health check

---

attributes/default.rb
metadata.rb
recipes/prometheus.rb
templates/default/prometheus.yml.erb

Part of https://github.com/logicalclocks/cloud-tickets/issues/26

[CLOUD-26] configure prometheus to push metrics to hopsworks-cloud

---

attributes/default.rb

Fixes https://logicalclocks.atlassian.net/browse/HOPSWORKS-2880

[HOPSWORKS-2880] update prometheus version to 2.31.1

---

files/default/rules/hive.rules.yml
files/default/rules/hopsfs.rules.yml
files/default/rules/hopsworks.rules.yml
files/default/rules/host.rules.yml
files/default/rules/yarn.rules.yml

Add additional metrics for the following: 
- HopsFS/Yarn
- Hopsworks
- Hive

Add alerting rules

---

recipes/grafana.rb
recipes/prometheus.rb
templates/default/dashboards_provisioning.yml.erb
templates/default/prometheus.yml.erb

Resolves https://github.com/logicalclocks/hopsworks-cloud/issues/3064

[HOPSWORKS-CLOUD] Ingore kserve Prometheus metrics if we build images for the Cloud

---

recipes/prometheus.rb

[HOPSWORKS-3164] Add

---

files/default/dashboards/hops/hopsworks.json

https://hopsworks.atlassian.net/browse/HWORKS-210

[HWORKS-210] jupyter threads fill up executor pool

---

files/default/dashboards/overview/clusteroverview.json
recipes/grafana.rb
templates/default/dashboards_provisioning.yml.erb

https://hopsworks.atlassian.net/browse/HWORKS-330

[HWORKS-330] Add cluster overview dashboard in Grafana

---

files/default/dashboards/overview/clusteroverview.json

https://hopsworks.atlassian.net/browse/HWORKS-330

[HWORKS-330] append - fix queries for Hopsworks

---

files/default/dashboards/hops/containers.json
files/default/dashboards/kserve/revision_metrics.json
files/default/dashboards/kubernetes/cluster.json

Also fixed some dashboards in kubernetes

[HWORKS-273] Fix container memory usage stats in dashboards

---

files/default/rules/db.rules.yml
files/default/rules/hive.rules.yml
files/default/rules/hopsfs.rules.yml
files/default/rules/yarn.rules.yml

https://hopsworks.atlassian.net/browse/HWORKS-326

[HWORKS-326] Fixes for prometheus alerting rules

---

files/default/rules/db.rules.yml

https://hopsworks.atlassian.net/browse/HWORKS-371

[HWORKS-371] Fire alert in case of absent metric

---

files/default/dashboards/hops/elastic.json

https://hopsworks.atlassian.net/browse/HWORKS-398

[HWORKS-398] OpenSearch Dashboard - elastic cluster status is wrong

---

files/default/dashboards/kserve/revision_metrics.json
files/default/dashboards/kubernetes/cluster.json
templates/default/prometheus.yml.erb

https://hopsworks.atlassian.net/browse/CLOUD-390

[CLOUD-390] Kubernetes upgrade

---

templates/default/rules/opensearch.rules.yml.erb

Fixes https://hopsworks.atlassian.net/browse/HWORKS-560

[HWORKS-560] Add an alert when approaching max number of shards in Opensearch

---

attributes/default.rb

https://hopsworks.atlassian.net/browse/HWORKS-564

[HWORKS-564] Bump Grafana version

---

templates/default/prometheus.yml.erb

https://hopsworks.atlassian.net/browse/HWORKS-833

[HWORKS-833] Template Consul datacenter

---

attributes/default.rb
metadata.rb
templates/default/rules/db.rules.yml.erb

https://hopsworks.atlassian.net/browse/HWORKS-847

[HWORKS-847] RonDB Global replication alert

---

files/default/dashboards/hops/onlinefs.json

[FSTORE-1111] OnlineFS monitoring shows wrong clusterj session count

---

files/default/dashboards/hops/onlinefs.json

[FSTORE-1121] Support Similarity Search in the Feature Store v1 - onlinefs monitoring

---

templates/default/alertmanager.service.erb
templates/default/node_exporter.service.erb
templates/default/nvml_monitor.service.erb
templates/default/prometheus.service.erb
templates/default/pushgateway.service.erb

https://hopsworks.atlassian.net/browse/HWORKS-946

[HWORKS-946] Extra After systemd units

---

attributes/default.rb
metadata.rb
recipes/node_exporter.rb
templates/default/node-exporter-consul.hcl.erb
templates/default/prometheus.yml.erb
templates/default/rules/host.rules.yml.erb

* [HWORKS-1061] Separate out of memory rules for ndbmtd nodes
[HWORKS-1061] Attribute to explicitly mark a node_exporter as ndbmtd node
* [HWORKS-1061] Fix pattern matching operator
* [HWORKS-1061] Decrease the ndbmtd available memory threshold
* [HWORKS-1061] Fix default
[HWORKS-1061]: https://hopsworks.atlassian.net/browse/HWORKS-1061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HWORKS-1061]: https://hopsworks.atlassian.net/browse/HWORKS-1061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HWORKS-1061]: https://hopsworks.atlassian.net/browse/HWORKS-1061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HWORKS-1061]: …

[HWORKS-1061] Separate out of memory rules for ndbmtd nodes

---

templates/default/rules/opensearch.rules.yml.erb

Fixes https://hopsworks.atlassian.net/browse/HWORKS-1146

[HWORKS-1146] Add alert for opensearch heap memory

---

files/default/dashboards/kserve/revision_metrics.json

[HWORKS-896] Resources dashboard for serving uses outdated kube state metrics queries (#150)
